baseurl = "http://consequently.org"
languageCode = "en-us"
title = "consequently.org: Greg Restall’s website"
RSSLink = "http://consequently.org/index.xml"

[params]
   description = "Greg Restall’s website"
   author = "Greg Restall"
   